apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`guestbook.derby.home`)
      priority: 10
      services:
        - name: {{ template "helm-guestbook.fullname" . }}
          port: 80
  tls:
    certResolver: default
    options: {}
